# Generated by Django 5.0.6 on 2024-07-01 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ms_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Office Location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Preferred Language'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
