# Generated by Django 5.0.6 on 2024-07-25 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('process_owner', models.CharField(blank=True, max_length=150, null=True)),
                ('strategy_alignment_score', models.CharField(blank=True, max_length=150, null=True)),
                ('financial_return_score', models.CharField(blank=True, max_length=150, null=True)),
                ('delivery_success_score', models.CharField(blank=True, max_length=150, null=True)),
                ('overall_score', models.CharField(blank=True, max_length=150, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=150, null=True)),
                ('service_technology_center', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_capex_cost', models.CharField(blank=True, max_length=150, null=True)),
                ('estimated_opex_cost', models.CharField(blank=True, max_length=150, null=True)),
                ('high_level_value_statement', models.TextField(blank=True, null=True)),
                ('forecasted_business_impact', models.TextField(blank=True, null=True)),
                ('forecast_customer_impact', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Converted', 'Converted'), ('Planning', 'Planning'), ('Revisit', 'Revisit'), ('Rejected', 'Rejected'), ('Draft', 'Draft')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opportunity',
            },
        ),
        migrations.CreateModel(
            name='OpportunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('oportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity')),
            ],
            options={
                'db_table': 'opportunity_comment',
            },
        ),
    ]
