# Generated by Django 5.0.6 on 2024-08-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycomment',
            name='status',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
