# Generated by Django 5.0.6 on 2024-08-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunitycomment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunitycomment',
            old_name='oportunity',
            new_name='opportunity',
        ),
    ]
