# Generated by Django 5.0.6 on 2024-08-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_rename_oportunity_opportunitycomment_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='business_benefit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
