# Generated by Django 5.0.6 on 2024-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_opportunity_business_benefit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='business_benefit',
            new_name='business_benefit_value',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='high_level_value_statement',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='estimated_cost_saving',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
