# Generated by Django 5.0.6 on 2024-08-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_rename_business_benefit_opportunity_business_benefit_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='forecasted_business_impact',
            new_name='current_pain_point_and_issue',
        ),
    ]
