# Generated by Django 5.0.6 on 2024-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0007_rename_forecasted_business_impact_opportunity_current_pain_point_and_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='division_type',
            field=models.CharField(choices=[('VSS', 'VSS'), ('VSC', 'VSC')], default='VSS', max_length=10),
        ),
    ]
