# Generated by Django 5.0.6 on 2024-08-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_opportunity_division_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='service_technology_center',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
