# Generated by Django 5.0.6 on 2024-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_alter_opportunity_service_technology_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='estimated_revenue_generation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
