# Generated by Django 5.0.6 on 2024-07-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisionlog',
            old_name='details',
            new_name='detail',
        ),
    ]
