# Generated by Django 5.0.6 on 2024-07-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_details_decisionlog_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='probability',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='severity',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
