# Generated by Django 5.0.6 on 2024-07-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionlog',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_category',
            field=models.CharField(blank=True, choices=[('Assembly Manufacturing', 'Assembly Manufacturing'), ('Communication', 'Communication'), ('Facility Readiness', 'Facility Readiness'), ('Customer', 'Customer'), ('Finance', 'Finance'), ('IT', 'IT'), ('Logistics', 'Logistics'), ('Machinery Manufacturing', 'Machinery Manufacturing'), ('Marketing', 'Marketing'), ('People', 'People'), ('Planning', 'Planning'), ('Procurement', 'Procurement'), ('Quality', 'Quality'), ('Safety', 'Safety')], max_length=100, null=True),
        ),
    ]
