# Generated by Django 5.0.6 on 2024-07-26 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_decisionlog_project_alter_risk_risk_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
