# Generated by Django 5.0.6 on 2024-07-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_risk_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionlog',
            name='impact',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='decisionlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('implemented', 'Implemented')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_category',
            field=models.CharField(blank=True, choices=[('assembly manufacturing', 'Assembly Manufacturing'), ('communication', 'Communication'), ('facility readiness', 'Facility Readiness'), ('customer', 'Customer'), ('finance', 'Finance'), ('it', 'IT'), ('logistics', 'Logistics'), ('machinery manufacturing', 'Machinery Manufacturing'), ('marketing', 'Marketing'), ('people', 'People'), ('planning', 'Planning'), ('procurement', 'Procurement'), ('quality', 'Quality'), ('safety', 'Safety')], max_length=100, null=True),
        ),
    ]
