# Generated by Django 5.0.6 on 2024-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_decisionlog_impact_alter_decisionlog_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='risk_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='severity',
            new_name='risk_level',
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='mitigation_actions',
            new_name='risk_response',
        ),
        migrations.AddField(
            model_name='risk',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='G', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='quality',
            field=models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='G', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='G', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('CANCELLED', 'CANCELLED')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='G', max_length=10),
        ),
    ]
