# Generated by Django 5.0.6 on 2024-07-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
