# Generated by Django 5.0.6 on 2024-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_phase_project_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='category',
            field=models.CharField(blank=True, choices=[('assembly_manufacturing', 'Assembly Manufacturing'), ('communication', 'Communication'), ('facility_readiness', 'Facility Readiness'), ('customer', 'Customer'), ('finance', 'Finance'), ('it', 'IT'), ('logistics', 'Logistics'), ('machinery_manufacturing', 'Machinery Manufacturing'), ('marketing', 'Marketing'), ('people', 'People'), ('planning', 'Planning'), ('procurement', 'Procurement'), ('quality', 'Quality'), ('safety', 'Safety')], max_length=100, null=True),
        ),
    ]
