# Generated by Django 5.0.6 on 2024-08-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_risk_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='division_type',
            field=models.CharField(choices=[('VSS', 'VSS'), ('VSC', 'VSC')], default='VSS', max_length=10),
        ),
    ]
