# Generated by Django 5.0.6 on 2024-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_costs_division_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costs',
            name='division_type',
        ),
        migrations.AddField(
            model_name='project',
            name='division_type',
            field=models.CharField(choices=[('VSS', 'VSS'), ('VSC', 'VSC')], default='VSS', max_length=10),
        ),
    ]
