# Generated by Django 5.0.6 on 2024-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_costs_division_type_project_division_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('Data', 'Data'), ('Application', 'Application'), ('Application and Data', 'Application and Data')], max_length=50, null=True),
        ),
    ]
