# Generated by Django 5.0.6 on 2024-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_rename_scrum_master_project_lead_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='general_manager',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('Data', 'Data'), ('Application', 'Application'), ('Application and Data', 'Application and Data'), ('Strategic Facility Projects', 'Strategic Facility Projects'), ('Regional Projects', 'Regional Projects')], max_length=50, null=True),
        ),
    ]
